baseurl = "http://lukewestby.com"
languageCode = "en-us"
title = "Don't laugh"
theme = "steam"
# disqusShortname = "spf13"
paginate = 10

[params]

	title = "In which"
	subtitle = "Luke tries too hard to be funny while talking about code"
	copyright = "Released under the MIT license."

	# You can choose between green, orange, red and blue.
	themeColor = "red"
	# Enable Google Analytics be inserting your tracking code
	googleAnalytics = ""

	# To provide some metadata for search engines and the about section in the footer
	# feel free to add a few information about you and your website.
	name = "Luke Westby"
	bio = "I'm cool because I use words like 'yo' and 'monad'"
	description = "This is literally the worst thing you'll ever read in your life"
	location = "" # optional
	twitter = "luke_dot_js" # optional
	github = "lukewestby" # optional

	# Enable a comment system
	# You can choose between Disqus or Google Plus by setting comments
	# to disqus or googleplus. For using Disqus you need to enter your
	# shortname in disqusShortname at the top of the configs.
	comments = "disqus"

	# Customize or translate the strings
	keepReadingStr = "Keep reading"
	backtotopStr = "Back to top"
	shareStr = "Share"
	pageNotFoundTitle = "404 - Page not found"
