baseurl = "http://lukewestby.com/"
languageCode = "en-us"
title = "Trouble (::)entrating"
theme = "steam"
disqusShortname = "lukewestby"
paginate = 10

[params]

	title = "Trouble (::)entrating"
	subtitle = "A code blog by Luke"
	copyright = "Released under the MIT license."

	# You can choose between green, orange, red and blue.
	themeColor = "red"
	# Enable Google Analytics be inserting your tracking code
	googleAnalytics = "UA-74412413-1"

	# To provide some metadata for search engines and the about section in the footer
	# feel free to add a few information about you and your website.
	name = "Luke Westby"
	bio = "Hi! I'm Luke. I'm a Partner at [HumbleSpark](https://humblespark.com) in Chicago, IL, USA and an avid fan of the [Elm programming language](http://elm-lang.org). I try to be as active as I can in the Elm community through [open source contribution](https://github.com/lukewestby), [community engagement](https://meetup.com/chicago-elm), writing, and speaking. Are you new to Elm and have questions about the language? Submit your topic [here](http://goo.gl/forms/u7QcFUuxsc)."
	description = "A code blog by Luke"
	location = "Chicago, IL, USA" # optional
	# twitter = "" # optional
	github = "lukewestby" # optional

	# Enable a comment system
	# You can choose between Disqus or Google Plus by setting comments
	# to disqus or googleplus. For using Disqus you need to enter your
	# shortname in disqusShortname at the top of the configs.
	comments = "disqus"

	# Customize or translate the strings
	keepReadingStr = "Keep reading"
	backtotopStr = "Back to top"
	shareStr = "Share"
	pageNotFoundTitle = "404 - Page not found"
